const uiTypes = {
  FAILED_LOGIN: 'FAILED_LOGIN',
  FAILED_LOGIN2: 'FAILED_LOGIN2',
  RESET_LOGIN: 'RESET_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  LOGOUT: 'LOGOUT',
}

const generalTypes = {
  LOADING_TRUE: 'LOADING_TRUE',
  LOADING_FALSE: 'LOADING_FALSE',
  CHANGE_LIGHT: 'CHANGE_LIGHT',
}

const API = 'api'

export {
  API,
  uiTypes,
  generalTypes,
}
